[http://www.numpy.org/](NumPy) is a Python library for efficient work with multi-dimensional arrays.

In [1]:
import numpy as np

In [2]:
# create an array from 0 to 30 increasing by 2
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [3]:
# reshape it to 5 by 3
n.reshape(-1, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [4]:
# do a element-wise computation:
n * n + n

array([  0,   6,  20,  42,  72, 110, 156, 210, 272, 342, 420, 506, 600,
       702, 812])

In [5]:
# generate an array of 7 zeros:
np.zeros(7)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
# or 3 ones:
np.ones(3)

array([ 1.,  1.,  1.])

In [7]:
# or a 3x3 identity matrix:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
# generate 7 random numbers:
np.random.random(7)

array([ 0.90715846,  0.52868906,  0.55664868,  0.82143732,  0.83819292,
        0.60724704,  0.41375378])

In [9]:
# or wrap an 2x3 array
w = np.array([[1, 3, 3, 7], [7, 3, 3, 1]])
w

array([[1, 3, 3, 7],
       [7, 3, 3, 1]])

In [10]:
# or 8 decimal numbers in the range 0 and 1 and reshape to 2x4
nt= np.linspace( 0, 1, 8).reshape(2, 4).T
nt

array([[ 0.        ,  0.57142857],
       [ 0.14285714,  0.71428571],
       [ 0.28571429,  0.85714286],
       [ 0.42857143,  1.        ]])

In [11]:
# or perform matrix multiplication, the same as w.dot(nt):
wnt = w @ nt
wnt

array([[  4.28571429,  12.28571429],
       [  1.71428571,   9.71428571]])

In [12]:
# find the inverse
iwnt = np.linalg.inv(wnt)
iwnt

array([[ 0.47222222, -0.59722222],
       [-0.08333333,  0.20833333]])

In [13]:
# check that A*A' = I:
wnt @ iwnt

array([[  1.00000000e+00,   1.13665691e-16],
       [  7.93016446e-18,   1.00000000e+00]])

In [14]:
# do some fun stuff:
chance_of_tornado = 0.01
tornados = np.random.binomial(1, chance_of_tornado, 1000000)
two_in_a_row = 0
for j in range(1, len(tornados) - 1):
    two_in_a_row += tornados[j] & tornados[j - 1]

print('{} tornados back to back in {} years'.format(two_in_a_row, 1000000/365))

99 tornados back to back in 2739.72602739726 years


For more info, take a look at: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html